from nlp_магия import найти_имена  

def test_найти_имена():  
    текст = "Анна Каренина приехала в Москву."  
    результат = найти_имена(текст)  
    assert len(результат) > 0  
    assert "Анна" in str(результат)  
