 - имя: Загрузить артефакт сборки
 использует: actions/download-artifact@v4.1.8
 с: 
 # Имя загружаемого артефакта. Если не указано, загружаются все артефакты для выполнения.
 имя: # необязательно
 # Путь назначения. Поддерживает базовое расширение тильды. По умолчанию используется $GITHUB_WORKSPACE
 путь: # необязательно
 # Шаблон глобуса, соответствующий загружаемым артефактам. Игнорируется, если указано имя.
 шаблон: # необязательно
 # При совпадении нескольких артефактов это изменяет поведение целевых каталогов. Если значение равно true, загруженные артефакты будут находиться в том же каталоге, который указан в path. Если значение равно false, загруженные артефакты будут извлечены в отдельные именованные каталоги в указанном пути.
 объединить несколько: # необязательно, по умолчанию false
 # Токен GitHub, используемый для аутентификации в GitHub API. Это необходимо при загрузке артефактов из другого репозитория или из другого запуска рабочего процесса. Если это не указано, действие попытается загрузить артефакты из текущего репозитория и текущего выполнения рабочего процесса.
 github-token: # необязательно
 # Владелец репозитория и название репозитория, соединенные символом «/». Если указан github-token, это репозиторий, из которого будут загружены артефакты.
 репозиторий: # необязательно, по умолчанию используется ${{ github.repository }}
 # Идентификатор выполнения рабочего процесса, из которого был загружен нужный для загрузки артефакт. Если указан github-token, это выполнение, из которого будут загружены артефакты.
 run-id: # необязательно, по умолчанию используется ${{ github.run_id }}

 
